name: imkit
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
    
  # Network
  socket_io_client: ^1.0.2
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  
  # Model
  json_annotation: ^4.4.0

  # Persistent Data
  shared_preferences: ^2.0.13
  floor: ^1.2.0

  # Photo
  photo_manager: ^2.1.2

  # Util
  enume: ^1.1.0
  crypto: ^3.0.1
  path_provider: ^2.0.9
  keyboard_dismisser: ^2.0.1
  cached_network_image: ^3.2.0
  popup_menu: 
    git:
      url: https://github.com/shangguanyanyan/popup_menu

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  build_runner: ^2.1.8

  # Network
  retrofit_generator: ^3.0.0+2

  # Model
  json_serializable: ^6.1.5

  # Persistent Data
  floor_generator: ^1.2.0

  #Util
  enume_generator: ^1.0.0
  collection: ^1.15.0
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages

flutter_intl:
  enabled: true
  class_name: IMKitS
  main_locale: zh
  arb_dir: lib/resources/l10n
  output_dir: lib/generated